@backend_HostAddress = http://localhost:5065

###

### Seed database
POST {{backend_HostAddress}}/seed
Content-Type: application/json

### Get all movies with categories
GET {{backend_HostAddress}}/movies
